# Generated by Django 4.2.18 on 2025-01-30 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ECG',
            fields=[
                ('diagnosis_id', models.AutoField(primary_key=True, serialize=False)),
                ('ecg_data', models.BinaryField()),
                ('processed_data_path', models.CharField(blank=True, max_length=255, null=True)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('interpretation', models.TextField(blank=True, null=True)),
                ('risk_level', models.CharField(choices=[('LOW', 'Faible'), ('MEDIUM', 'Moyen'), ('HIGH', 'Élevé')], default='LOW', max_length=10)),
                ('plots', models.BinaryField(blank=True, null=True)),
                ('patient_notified', models.BooleanField(default=False)),
                ('doctor_notified', models.BooleanField(default=False)),
                ('doctor_notes', models.TextField(blank=True, null=True)),
                ('diagnosis_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ecgs', to='account_app.patient')),
            ],
            options={
                'verbose_name': 'ECG',
                'verbose_name_plural': 'ECGs',
                'ordering': ['-created_at'],
            },
        ),
    ]
