# Generated by Django 4.2.18 on 2025-01-30 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecg',
            name='plots',
            field=models.BinaryField(blank=True, editable=True, null=True),
        ),
    ]
