# Generated by Django 4.2.18 on 2025-01-18 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0001_initial'),
        ('patient_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecg',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ecgs', to='account_app.patient'),
        ),
    ]
