# Generated by Django 4.2.18 on 2025-01-18 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient_app', '0002_alter_ecg_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ecg',
            name='record_id',
        ),
    ]
