# Generated by Django 4.2.18 on 2025-02-07 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_app', '0002_alter_ecg_plots'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecg',
            name='cycles_analysis_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
