# Generated by Django 4.2.18 on 2025-02-10 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_app', '0003_ecg_cycles_analysis_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecg',
            name='has_pathology_details',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ecg',
            name='pathology_confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ecg',
            name='pathology_interpretation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ecg',
            name='pathology_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
