# Generated by Django 4.2.18 on 2025-01-29 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_app', '0003_remove_ecg_record_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecg',
            name='processed_data_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
